import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./(components)/Header";
import Konten from "./(components)/Konten";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Jikan",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-jikan-secondary text-jikan-neutral`}>
        <Header />
        <Konten>{children}</Konten>
      </body>
    </html>
  );
}
